### PR TITLE
kubricify shapenet

### PR DESCRIPTION
**Pull request by IssamLaradji**
This pull request is still at its starting point. The goal is to wrap "shapenet" with an API that allows us to "kubricify" it using some of the functions from https://github.com/google-research/kubric/blob/master/kubric/assets/asset_preprocessing.py, right @Qwlouse ?

### CODE REVIEW

**Comment by IssamLaradji** [comment]
This pull request is still at its starting point to get a discussion going. The goal is to wrap "shapenet" with an API that allows us to "kubricify" it, right @Qwlouse ?

**Comment by Qwlouse** [comment]
Perfect! 👍

**Comment by taiya** [comment]
You can mark a PR as "draft" by the way (removes the need for the WIP flag) ;)

**Comment by taiya** [comment]
This PR was abandoned it seems.
Closing

**Pull request closed without merging**
